"""Repository protocols used when extracting legacy persistence incrementally."""
from __future__ import annotations
from typing import Any, Protocol

class ReservationRepository(Protocol):
    def list(self) -> list[dict[str, Any]]: ...

class ConversationStateRepository(Protocol):
    def get(self, key: str) -> dict[str, Any]: ...
    def put(self, key: str, value: dict[str, Any]) -> None: ...

class ClientMemoryRepository(Protocol):
    def get(self, key: str) -> dict[str, Any]: ...
    def put(self, key: str, value: dict[str, Any]) -> None: ...

class MetricsRepository(Protocol):
    def append(self, event: dict[str, Any]) -> None: ...
